#!/bin/bash

#!/bin/bash
# 设置 Python 依赖加载路径，我们默认设置在 third_party 目录
export PYTHONPATH="./third_party:$PYTHONPATH"

# 运行数据库迁移
/var/lang/python310/bin/python3.10 manage.py migrate --noinput

# 收集静态文件
/var/lang/python310/bin/python3.10 manage.py collectstatic --noinput

# 启动 Django 应用
/var/lang/python310/bin/python3.10 manage.py runserver 0.0.0.0:9000
